name: footwear_app
description: A Flutter app for browsing and purchasing footwear.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  lottie: ^1.2.0
  cupertino_icons: ^1.0.8
  intl: ^0.17.0
  animated_splash_screen: ^1.3.0
  provider: ^6.1.2
  http: ^1.2.1
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  go_router: ^14.1.4
  flutter_staggered_grid_view: ^0.7.0
  carousel_slider: ^4.2.1
  firebase_auth: ^5.0.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/banner1.jpg
    - assets/images/banner2.jpg
    - assets/images/banner3.jpg
    - assets/images/tarps.jpg
    - assets/images/shadenets.jpg
    - assets/images/pipes.jpg
    - assets/images/seasonal.jpg
    - assets/images/decorative.jpg
    - assets/icons/tandhanlogo.png
    - assets/images/app_bar.png

fonts:
  - family: Montserrat
    fonts:
      - asset: fonts/Montserrat-Regular.ttf
      - asset: fonts/Montserrat-Bold.ttf
        weight: 700
      - asset: fonts/Montserrat-Italic.ttf
        style: italic
      - asset: fonts/Montserrat-BoldItalic.ttf
        weight: 700
        style: italic