name: footwear_app
description: A Flutter app for browsing and purchasing footwear.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  animated_splash_screen: ^1.3.0
  provider: ^6.1.2               # State management
  http: ^1.2.1                  # Networking (for fetching product data)
  cached_network_image: ^3.3.1   # Displaying images from the network efficiently
  flutter_svg: ^2.0.10+1            # Support for SVG icons
  go_router: ^14.1.4             # Navigation
  flutter_staggered_grid_view: ^0.7.0 # UI components for staggered grid views
  carousel_slider: ^4.2.1       # Carousel slider for image carousels
  firebase_auth: ^5.0.0         # Authentication/user management
  shared_preferences: ^2.2.3    # Local data storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  # Folder for icon assets (PNG or SVG)
  assets:
    - assets/images/banner1.jpg
    - assets/images/banner2.jpg
    - assets/images/banner3.jpg
    - assets/images/tarps.jpg
    - assets/images/shadenets.jpg
    - assets/images/pipes.jpg
    - assets/images/seasonal.jpg
    - assets/images/decorative.jpg
    - assets/images/others.jpg
    - assets/icons/tandhanlogo.png
